// What goes on the virtual wedgie's flash: every file in /fw/manifest.json (published from
// firmware/ by tools/fw.mjs), with one app in apps.json (the one it runs), plus the few things a real
// board has that the repo does not.

export type Manifest = { version: string; files: { name: string; size: number; sha256: string }[]; carts: App[] };
type App = { mod: string; name?: string; entry?: string; usb?: boolean; about?: string; v?: string };

/** extra: an app from outside the manifest (a GitHub repo's): its files, and it's the app it runs. */
export async function loadFlash(base = "/fw/", app = "hello", extra?: { app: App; files: Record<string, Uint8Array> }) {
  const manifest: Manifest = await (await fetch(base + "manifest.json", { cache: "no-cache" })).json();
  const files: Record<string, string | Uint8Array> = {};
  await Promise.all(manifest.files.map(async (f) => {
    // A compiled app file (.mpy, tools/mpy.py) runs from its source here (fw/src/): the Timer form below
    // edits the source, and the emulator's heap doesn't need the bytecode. The board gets the .mpy.
    if (f.name.endsWith(".mpy")) {
      const py = f.name.replace(/\.mpy$/, ".py"), s = await fetch(base + "src/" + py, { cache: "no-cache" });
      if (s.ok) { files[py] = await s.text(); return; }
    }
    const r = await fetch(base + f.name, { cache: "no-cache" });
    if (!r.ok) throw new Error(`fw/${f.name}: HTTP ${r.status}`);
    files[f.name] = /\.(py|json)$/.test(f.name) ? await r.text() : new Uint8Array(await r.arrayBuffer());
  }));
  files["apps.json"] = JSON.stringify(manifest.carts.filter((c) => c.mod === app).map(({ mod, name, entry, usb, about, v }) => ({ mod, name, entry, usb, about, v })));
  if (extra) {
    for (const [n, b] of Object.entries(extra.files)) files[n] = /\.(py|json)$/.test(n) ? new TextDecoder().decode(b) : b;
    const { mod, name, entry, usb, about, v } = extra.app;
    files["apps.json"] = JSON.stringify([{ mod, name, entry, usb, about, v }]);
  }
  emulatorOnly(files);
  return { manifest, files };
}

// On the board an app with an `entry` (usbwallet.run) may own the CPU in a loop forever. The
// emulator is one thread, so an app that also offers start()/stop() (the Timer form, which the
// firmware keeps for exactly this) is run that way instead: it starts itself at import. Apps whose
// entry has no Timer form (demo.run) keep their entry and own the worker; keys still work.
function emulatorOnly(files: Record<string, string | Uint8Array>) {
  const appsJson = files["apps.json"];
  if (typeof appsJson === "string") {
    try {
      const apps: App[] = JSON.parse(appsJson);
      for (const a of apps) {
        const src = files[a.mod + ".py"];
        if (!a.entry || typeof src !== "string") continue;
        if (/^def start\(/m.test(src) && /^def stop\(/m.test(src)) {
          delete a.entry;
          files[a.mod + ".py"] = src + "\n\nstart()  # virtual wedgie: Timer form, see src/emu/flash.ts\n";
        }
      }
      files["apps.json"] = JSON.stringify(apps);
    } catch { /* leave a broken apps.json broken: the launcher shows it the way the board would */ }
  }
  // Saves: the page can't read the flash while an app owns the CPU, so every save.store/delete also
  // prints one @emusave line; the page keeps them (and can edit them) and hands them back at the next boot.
  if (typeof files["save.py"] === "string") files["save.py"] += SAVE_TAP;
  // No secure chip here: the wallet runs on a software key, like a bare Pico with ALLOW_SOFT_KEY.
  if (!("secrets.py" in files)) files["secrets.py"] = SECRETS;
  // A fixed throwaway key so the virtual wallet's address is the same on every boot. Never a real key.
  if (!("key.bin" in files)) files["key.bin"] = Uint8Array.from({ length: 32 }, (_, i) => i + 1);
}

const SAVE_TAP = `

# virtual wedgie (src/emu/flash.ts): tell the page about every save, so it outlives this run
_store0, _delete0 = store, delete


def store(name, data):
    _store0(name, data)
    import binascii
    raw = isinstance(data, (bytes, bytearray, memoryview))
    b = bytes(data) if raw else json.dumps(data).encode()
    print("@emusave " + json.dumps({"game": game, "name": name, "ext": ".bin" if raw else ".json", "b64": binascii.b2a_base64(b).decode().strip()}))


def delete(name):
    _delete0(name)
    print("@emusave " + json.dumps({"game": game, "name": name, "del": True}))
`;

const SECRETS = `# generated by the virtual wedgie; a real secrets.py never leaves the board
DEVICE_NAME = "virtual wedgie"
EXPECTED_CHAIN_ID = None
EXPECTED_VAULT = None
EXPECTED_TOKEN = None
ALLOW_LOCK = False
ALLOW_GENKEY = False
ALLOW_SOFT_KEY = True   # no chip in the emulator: run the wallet on a software key anyway
`;

// firmware/main.py, except the slot runs on a Timer (slot.start) instead of owning the CPU
// (slot.run): the Worker is one thread, and apps like hello tick on Timers of their own.
export const BOOT = `import sys
try:
    import boot
except Exception as e:
    sys.print_exception(e)
try:
    import lcd
    import wedgie
    import loader
    _a = wedgie.active()
    wedgie.lines()
    loader.load(_a["mod"] if _a else "slot")
    import slot
    slot.start()
except Exception as e:
    sys.print_exception(e)
`;
