// What goes on the virtual wedgie's flash: every file in /fw/manifest.json (published from
// firmware/ by tools/fw.mjs), with one app in apps.json (the one it runs), plus the few things a real
// board has that the repo does not.

export type Manifest = { version: string; files: { name: string; size: number; sha256: string }[]; carts: App[] };
type App = { mod: string; name?: string; entry?: string; usb?: boolean; about?: string; v?: string };

export async function loadFlash(base = "/fw/", app = "hello") {
  const manifest: Manifest = await (await fetch(base + "manifest.json", { cache: "no-cache" })).json();
  const files: Record<string, string | Uint8Array> = {};
  await Promise.all(manifest.files.map(async (f) => {
    const r = await fetch(base + f.name, { cache: "no-cache" });
    if (!r.ok) throw new Error(`fw/${f.name}: HTTP ${r.status}`);
    files[f.name] = /\.(py|json)$/.test(f.name) ? await r.text() : new Uint8Array(await r.arrayBuffer());
  }));
  files["apps.json"] = JSON.stringify(manifest.carts.filter((c) => c.mod === app).map(({ mod, name, entry, usb, about, v }) => ({ mod, name, entry, usb, about, v })));
  emulatorOnly(files);
  return { manifest, files };
}

// On the board an app with an `entry` (usbwallet.run) may own the CPU in a loop forever. The
// emulator is one thread, so an app that also offers start()/stop() (the Timer form, which the
// firmware keeps for exactly this) is run that way instead: it starts itself at import. Apps whose
// entry has no Timer form (demo.run) keep their entry and own the worker; keys still work.
function emulatorOnly(files: Record<string, string | Uint8Array>) {
  const appsJson = files["apps.json"];
  if (typeof appsJson === "string") {
    try {
      const apps: App[] = JSON.parse(appsJson);
      for (const a of apps) {
        const src = files[a.mod + ".py"];
        if (!a.entry || typeof src !== "string") continue;
        if (/^def start\(/m.test(src) && /^def stop\(/m.test(src)) {
          delete a.entry;
          files[a.mod + ".py"] = src + "\n\nstart()  # virtual wedgie: Timer form, see src/emu/flash.ts\n";
        }
      }
      files["apps.json"] = JSON.stringify(apps);
    } catch { /* leave a broken apps.json broken: the launcher shows it the way the board would */ }
  }
  // No secure chip here: the wallet runs on a software key, like a bare Pico with ALLOW_SOFT_KEY.
  if (!("secrets.py" in files)) files["secrets.py"] = SECRETS;
  // A fixed throwaway key so the virtual wallet's address is the same on every boot. Never a real key.
  if (!("key.bin" in files)) files["key.bin"] = Uint8Array.from({ length: 32 }, (_, i) => i + 1);
}

const SECRETS = `# generated by the virtual wedgie; a real secrets.py never leaves the board
DEVICE_NAME = "virtual wedgie"
EXPECTED_CHAIN_ID = None
EXPECTED_VAULT = None
EXPECTED_TOKEN = None
ALLOW_LOCK = False
ALLOW_GENKEY = False
ALLOW_SOFT_KEY = True   # no chip in the emulator: run the wallet on a software key anyway
`;

// firmware/main.py, except the slot runs on a Timer (slot.start) instead of owning the CPU
// (slot.run): the Worker is one thread, and apps like hello tick on Timers of their own.
export const BOOT = `import sys
try:
    import boot
except Exception as e:
    sys.print_exception(e)
try:
    import lcd
    import wedgie
    import loader
    _a = wedgie.active()
    loader.load(_a["mod"] if _a else "slot")
    import slot
    slot.start()
except Exception as e:
    sys.print_exception(e)
`;
